# .air.toml
root = "."
tmp_dir = "tmp"

[watch]
poll = true
poll_interval = "1000ms"

[build]
cmd = "GOWORK=off go build -o ./tmp/main ."
bin = "./tmp/main"
include_ext = ["go", "toml", "mod"]
exclude_dir = ["tmp", "vendor"]
log = "air.log"

[misc]
clean_on_exit = true